[workspace]
members = [
  "bidi",
  "bidi/generate",
  "strip-ansi-escapes",
  "wezterm",
  "wezterm-dynamic",
  "wezterm-gui",
  "wezterm-mux-server",
  "wezterm-ssh"
]
resolver = "2"
exclude = [
  "termwiz/codegen"
]

[profile.release]
opt-level = 3
# debug = 1

[profile.dev]
# https://jakedeichert.com/blog/reducing-rust-incremental-compilation-times-on-macos-by-70-percent/
split-debuginfo = "unpacked"

[patch.crates-io]
xcb = {version="1.1.1", git="https://github.com/wez/rust-xcb", branch="ffi"}
mlua = {version="0.8.0-beta.4", git="https://github.com/khvzak/mlua", branch="master"}
